### ISSUE TITLE
Some typos

### ISSUE THREAD

**Issue by kikadf** [wulf7/libudev-devd#10]
In [udev-utils.c](https://github.com/wulf7/libudev-devd/blob/073aeac021c8b659d74c841d62ba181eb2420e02/udev-utils.c#L134), in the subsystems created an empty item, so [fnmatch](https://github.com/wulf7/libudev-devd/blob/073aeac021c8b659d74c841d62ba181eb2420e02/udev-utils.c#L158)'s subsystems[i].syspath arg will be empty.

In [udev-device.c](https://github.com/wulf7/libudev-devd/blob/073aeac021c8b659d74c841d62ba181eb2420e02/udev-device.c#L102) ud should be udev.

**Comment by wulf7** [comment]
Committed, thanks!
